package jenovas.github.io.algocrafterexample.ui.screens.legal.sub

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.navigation.NavHostController
import com.composables.icons.lucide.ArrowLeft
import com.composables.icons.lucide.Lucide
import jenovas.github.io.algocrafterexample.ui.components.SharedScaffold
import jenovas.github.io.algocrafterexample.ui.navigation.LegalScreens
import jenovas.github.io.algocrafterexample.ui.navigation.ObserveAsEvents
import jenovas.github.io.algocrafterexample.ui.navigation.safeNavigateUp
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalHeading
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalScreenContentState
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalScreenEffect
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalScreenEvent
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalSection
import jenovas.github.io.algocrafterexample.ui.screens.legal.LegalViewModel
import org.koin.androidx.compose.koinViewModel

@Composable
fun AIDisclaimerScreen(
    navController: NavHostController,
    viewModel: LegalViewModel = koinViewModel(viewModelStoreOwner = navController.getBackStackEntry<LegalScreens>())
) {
    val state by viewModel.state.collectAsStateWithLifecycle()

    ObserveAsEvents(viewModel.effects) { effect ->
        when (effect) {
            is LegalScreenEffect.NavigateBack -> navController.safeNavigateUp()
            else -> {}
        }
    }

    AIDisclaimerScreenContent(
        state = state.contentState,
        onEvent = viewModel::handleEvent,
    )
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun AIDisclaimerScreenContent(
    state: LegalScreenContentState,
    onEvent: (LegalScreenEvent) -> Unit,
) {
    val scrollState = rememberScrollState()
    SharedScaffold(
        topBarTitle = "AI Disclaimer",
        topBarImageVector = Lucide.ArrowLeft,
        topBarOnEvent = { onEvent(LegalScreenEvent.NavigateBack) },
        bottomBarTitle = "Accept and Continue",
        bottomBarEnabled = true,
        bottomBarOnEvent = {
            onEvent(LegalScreenEvent.SetAIDisclaimerAccepted(true))
            onEvent(LegalScreenEvent.NavigateBack)
        }
    ) {
        Column(
            modifier = Modifier
                .weight(1f)
                .verticalScroll(scrollState)
                .padding(horizontal = 16.dp)
        ) {
            AIDisclaimerScreenLegalSection()
        }
    }
}

@Composable
private fun AIDisclaimerScreenLegalSection() {
    LegalHeading(text = "AI Analyzer Disclaimer")

    Text(
        text = "Before using the AI Analyzer, please read and accept the following terms:",
        style = MaterialTheme.typography.bodyLarge,
        color = MaterialTheme.colorScheme.onBackground
    )

    Spacer(modifier = Modifier.height(16.dp))

    LegalSection(
        title = "Not a Financial Advisor",
        content = "The AI Analyzer provided in this App is not a licensed financial advisor and does not offer personalized financial or investment advice. The analysis and suggestions generated by the AI are based on automated data processing and algorithms and should be treated as educational information only.",
        number = 1
    )

    LegalSection(
        title = "AI as a Tool, Not a Decision Maker",
        content = "The AI Analyzer is a supportive tool designed to assist with analyzing trading strategies, but it should not be relied upon as a decision-making authority. It is intended to provide supplemental information only and is not a substitute for your own judgment or decision-making.",
        number = 2
    )

    LegalSection(
        title = "AI May Make Errors",
        content = "The AI Analyzer is an automated tool, and like any software, it may make mistakes or provide information that is incomplete, inaccurate, or outdated. The analysis provided should not be taken as fact without further verification and testing.",
        number = 3
    )

    LegalSection(
        title = "AI Is Not Infallible",
        content = "AI-generated analysis is based on historical data patterns and may not account for future market conditions or unforeseen events. Users should understand that AI models are not capable of accurately predicting market behavior or outcomes.",
        number = 4
    )

    LegalSection(
        title = "Do Not Rely Solely on AI",
        content = "Users are strongly encouraged not to rely solely on the AI Analyzer when making financial decisions. You should always do your own research, conduct thorough testing, and verify all suggestions made by the AI before making any changes to your trading strategies.",
        number = 5
    )

    LegalSection(
        title = "Not Tailored to Individual Needs",
        content = "The AI analysis is based on general data inputs and does not take into account your personal financial situation, investment goals, or risk tolerance. Users must ensure that any suggestions align with their unique financial circumstances.",
        number = 6
    )

    LegalSection(
        title = "User Responsibility",
        content = "You acknowledge and agree that you are solely responsible for any trading decisions or financial actions you take based on the AI Analyzer's suggestions. The creators of this App are not responsible for any financial losses, damages, or consequences resulting from the use of the AI Analyzer.",
        number = 7
    )

    LegalSection(
        title = "Consult a Professional",
        content = "For personalized financial advice, always consult a qualified financial advisor. The AI Analyzer is a tool for research and education, and it cannot replace the personalized insight provided by a licensed professional.",
        number = 8
    )

    LegalSection(
        title = "No Tax or Legal Advice",
        content = "The AI Analyzer does not provide legal or tax advice. Users should consult with qualified professionals to understand the tax or legal implications of their financial strategies.",
        number = 9
    )

    LegalSection(
        title = "AI Evolution and Model Changes",
        content = "The AI Analyzer may be updated over time as new versions of the AI model become available. Results and suggestions may vary as the AI evolves, and users should be aware that different outputs may be produced by different versions of the AI model.",
        number = 10
    )

    LegalSection(
        title = "No Human Oversight",
        content = "The analysis provided by the AI Analyzer is fully automated without human oversight or review. The App's creators do not independently verify the accuracy of the AI's recommendations.",
        number = 11
    )

    LegalSection(
        title = "Use of Third-Party AI Models",
        content = "The AI Analyzer is powered by third-party AI models, including but not limited to ChatGPT and Gemini. We do not control the behavior of these models, and we disclaim any responsibility for inaccuracies, biases, or service interruptions caused by third-party AI systems.",
        number = 12
    )

    Spacer(modifier = Modifier.height(24.dp))
}